### ISSUE TITLE
Advance create platform dialog as soon as platform has been selected

### ISSUE THREAD

**Issue by jjo93sa** [stackhpc/azimuth#33]
We've had a question from our Azimuth users whether, when  an appliance has been selected in the "Create a new platform / Pick a platform type" dialog, can it automatically progress to the "Configure platform" page? This would be rather than the current workflow that requires clicking the "Next" button. Thanks

**Comment by JohnGarbutt** [comment]
I like this idea, note we still want users to return to the previous dialog and select a different platform. But generally it seems good to go straight to the questions once you click on our chosen platform.

**Comment by mkjpryor** [comment]
This is fixed in recent versions.
