### ISSUE TITLE
Some errors make the screen go blank, need to be more defensive?

### ISSUE THREAD

**Issue by JohnGarbutt** [stackhpc/azimuth#34]
For example, if you use the CRD driver, you can delete a cluster type, but still have a cluster of that type, and the whole screen goes blank. There are some react error messages suggesting we are missing some error handlers to pop up a more friendly error message, so we fail more gracefully. These are mostly unexpected cases, like the choices param not being well formed in ui meta causing the screen to go blank.

**Comment by mkjpryor** [comment]
React has error boundaries, which we should probably use to not show a blank screen. But more generally we need to be more defensive when referenced objects are missing, which is more difficult.

**Comment by m-bull** [comment]
Can also occur when a flavor that a platform is started with doesn't exist anymore.

**Comment by mkjpryor** [comment]
Superseded by #58
