### ISSUE TITLE
Create cluster failed in 500

### ISSUE THREAD

**Issue by jjo93sa** [stackhpc/azimuth#35]
FO] [2023-02-23 14:10:37,613] [azimuth.cluster_engine.drivers.awx.driver:108] [ThreadPoolExecutor-0_1] [johannesr@graphcore.ai] [johannesr@graphcore.ai] Found 2 inventories
--
  | Log labelsappazimuthcomponentapicontainerapifilename/var/log/pods/azimuth_azimuth-api-665cccdc4b-m2c7z_c6dc809a-f1b3-4400-9e0a-5a9c276cc828/api/0.loginstanceazimuthjobazimuth/azimuthnamespaceazimuthnode_nameazimuth-cl1-md-0-5e2cfe39-sbz78podazimuth-api-665cccdc4b-m2c7zstreamstdoutDetected fieldsTime1677161437613tsNs1677161437613671193 | Log labels |   | app | azimuth |   | component | api |   | container | api |   | filename | /var/log/pods/azimuth_azimuth-api-665cccdc4b-m2c7z_c6dc809a-f1b3-4400-9e0a-5a9c276cc828/api/0.log |   | instance | azimuth |   | job | azimuth/azimuth |   | namespace | azimuth |   | node_name | azimuth-cl1-md-0-5e2cfe39-sbz78 |   | pod | azimuth-api-665cccdc4b-m2c7z |   | stream | stdout | Detected fields |   | Time | 1677161437613 |   | tsNs | 1677161437613671193
Log labels
  | app | azimuth
  | component | api
  | container | api
  | filename | /var/log/pods/azimuth_azimuth-api-665cccdc4b-m2c7z_c6dc809a-f1b3-4400-9e0a-5a9c276cc828/api/0.log
  | instance | azimuth
  | job | azimuth/azimuth
  | namespace | azimuth
  | node_name | azimuth-cl1-md-0-5e2cfe39-sbz78
  | pod | azimuth-api-665cccdc4b-m2c7z
  | stream | stdout
Detected fields
  | Time | 1677161437613
  | tsNs | 1677161437613671193
  |   | 2023-02-23 14:10:37 | 172.21.36.128 - - [23/Feb/2023:14:10:37 +0000] "POST /api/tenancies/3a7dd6b6832a4dc2bf0d1cf3784f943b/clusters/ HTTP/1.1" 500 145 "https://portal.apps.gbnwp-cl1.ipu.graphcore.ai/tenancies/3a7dd6b6832a4dc2bf0d1cf3784f943b/platforms" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0"
  |   | 2023-02-23 14:10:37 | KeyError: 'cluster_name'
  |   | 2023-02-23 14:10:37 | name = params.pop("cluster_name")
  |   | 2023-02-23 14:10:37 | File "/application/azimuth/cluster_engine/drivers/awx/driver.py", line 383, in _from_inventory
  |   | 2023-02-23 14:10:37 | _ = self._from_inventory(inventory, ctx)
  |   | 2023-02-23 14:10:37 | File "/application/azimuth/cluster_engine/drivers/awx/driver.py", line 550, in create_cluster
  |   | 2023-02-23 14:10:37 | return f(*args, **kwargs)
  |   | 2023-02-23 14:10:37 | File "/application/azimuth/cluster_engine/drivers/awx/driver.py", line 37, in wrapper
  |   | 2023-02-23 14:10:37 | cluster = self._driver.create_cluster(
  |   | 2023-02-23 14:10:37 | File "/application/azimuth/cluster_engine/engine.py", line 280, in create_cluster
  |   | 2023-02-23 14:10:37 | cluster = cluster_manager.create_cluster(
  |   | 2023-02-23 14:10:37 | File "/application/azimuth/views.py", line 971, in clusters
  |   | 2023-02-23 14:10:37 | return view(*args, **kwargs)
  |   | 2023-02-23 14:10:37 | File "/application/azimuth/views.py", line 61, in wrapper
  |   | 2023-02-23 14:10:37 | return view(*args, **kwargs)
  |   | 2023-02-23 14:10:37 | File "/application/azimuth/views.py", line 113, in wrapper
  |   | 2023-02-23 14:10:37 | return view(*args, **kwargs)
  |   | 2023-02-23 14:10:37 | File "/application/azimuth/views.py", line 183, in wrapper
  |   | 2023-02-23 14:10:37 | return view(*args, **kwargs)
  |   | 2023-02-23 14:10:37 | File "/application/azimuth/views.py", line 141, in wrapper
  |   | 2023-02-23 14:10:37 | return func(*args, **kwargs)
  |   | 2023-02-23 14:10:37 | File "/usr/local/lib/python3.9/site-packages/rest_framework/decorators.py", line 50, in handler
  |   | 2023-02-23 14:10:37 | response = handler(request, *args, **kwargs)
  |   | 2023-02-23 14:10:37 | File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
  |   | 2023-02-23 14:10:37 | raise exc
  |   | 2023-02-23 14:10:37 | File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
  |   | 2023-02-23 14:10:37 | self.raise_uncaught_exception(exc)
  |   | 2023-02-23 14:10:37 | File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
  |   | 2023-02-23 14:10:37 | response = self.handle_exception(exc)
  |   | 2023-02-23 14:10:37 | File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
  |   | 2023-02-23 14:10:37 | return self.dispatch(request, *args, **kwargs)
  |   | 2023-02-23 14:10:37 | File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
  |   | 2023-02-23 14:10:37 | return view_func(*args, **kwargs)
  |   | 2023-02-23 14:10:37 | File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  |   | 2023-02-23 14:10:37 | response = wrapped_callback(request, *callback_args, **callback_kwargs)
  |   | 2023-02-23 14:10:37 | File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
  |   | 2023-02-23 14:10:37 | response = get_response(request)
  |   | 2023-02-23 14:10:37 | File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
  |   | 2023-02-23 14:10:37 | Traceback (most recent call last):
  |   | 2023-02-23 14:10:37 | [ERROR] [2023-02-23 14:10:37,106] [django.request:241] [ThreadPoolExecutor-0_0] Internal Server Error: /api/tenancies/3a7dd6b6832a4dc2bf0d1cf3784f943b/clusters/
  | Log labelsappazimuthcomponentapicontainerapifilename/var/log/pods/azimuth_azimuth-api-665cccdc4b-m2c7z_c6dc809a-f1b3-4400-9e0a-5a9c276cc828/api/0.loginstanceazimuthjobazimuth/azimuthnamespaceazimuthnode_nameazimuth-cl1-md-0-5e2cfe39-sbz78podazimuth-api-665cccdc4b-m2c7zstreamstderrDetected fieldsTime1677161437137tsNs1677161437137744717 | Log labels |   | app | azimuth |   | component | api |   | container | api |   | filename | /var/log/pods/azimuth_azimuth-api-665cccdc4b-m2c7z_c6dc809a-f1b3-4400-9e0a-5a9c276cc828/api/0.log |   | instance | azimuth |   | job | azimuth/azimuth |   | namespace | azimuth |   | node_name | azimuth-cl1-md-0-5e2cfe39-sbz78 |   | pod | azimuth-api-665cccdc4b-m2c7z |   | stream | stderr | Detected fields |   | Time | 1677161437137 |   | tsNs | 1677161437137744717
Log labels
  | app | azimuth
  | component | api
  | container | api
  | filename | /var/log/pods/azimuth_azimuth-api-665cccdc4b-m2c7z_c6dc809a-f1b3-4400-9e0a-5a9c276cc828/api/0.log
  | instance | azimuth
  | job | azimuth/azimuth
  | namespace | azimuth
  | node_name | azimuth-cl1-md-0-5e2cfe39-sbz78
  | pod | azimuth-api-665cccdc4b-m2c7z
  | stream | stderr
Detected fields
  | Time | 1677161437137
  | tsNs | 1677161437137744717
  |   | 2023-02-23 14:10:37 | 172.18.120.192 - - [23/Feb/2023:14:10:37 +0000] "GET /api/tenancies/4f19cf5df697497e9222505361cf75b8/quotas/ HTTP/1.1" 200 370 "https://portal.apps.gbnwp-cl1.ipu.graphcore.ai/tenancies/4f19cf5df697497e9222505361cf75b8/platforms" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15"

**Comment by mkjpryor** [comment]
This seems to be fixed. Please open a new issue if it occurs again.
