### ISSUE TITLE
Enable per appliance filtering or other specification of applicable flavours

### ISSUE THREAD

**Issue by jjo93sa** [stackhpc/azimuth#39]
It would be most useful to have the capability of filtering the list of flavours, or otherwise specifying a list of applicable flavours, per appliance type. A trivial examples: 

- Present only "Intel" flavours in the dropdown for appliances dedicated to Intel workloads
- Present only flavours with RAM > 128 GB for appliances requiring large allocations

**Comment by mkjpryor** [comment]
Filtering against CPU, RAM and root disk should already work.

Filtering against other characteristics of a flavor could be implemented by implementing filtering for specific traits on the flavor. This way, Azimuth itself doesn't need to have any specific knowledge of which traits mean what - it would be encoded in the ui-meta of the appliance and the traits applied to the flavors in OpenStack.

**Comment by mkjpryor** [comment]
Filtering by traits has been implemented.
